version: "3"

rpc:
  # TCP address:port for listening.
  listen: tcp://127.0.0.1:6001

server:
  command: "php /home/app/src/public/index.php"
  relay: pipes
  env:
    - APP_RUNTIME: Paysera\RoadRunnerBundle\Runtime\Runtime
    - XDEBUG_SESSION: "sm-rr-skeleton"
    - PHP_IDE_CONFIG: serverName=sm-rr-skeleton

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  pool:
    num_workers: 1
    debug: true
    max_jobs: 1
    supervisor:
      # watch_tick defines how often to check the state of the workers (seconds)
      watch_tick: 1s
      # ttl defines maximum time worker is allowed to live (seconds)
      ttl: 0
      # idle_ttl defines maximum duration worker can spend in idle mode after
      # first use. Disabled when 0 (seconds)
      idle_ttl: 60s
      # exec_ttl defines maximum lifetime per job (seconds)
      exec_ttl: 60s
      # max_worker_memory limits memory usage per worker (MB)
      max_worker_memory: 100

  ssl:
    # host and port separated by semicolon (default :443)
    address: :3002
    redirect: true
    cert: /etc/https/local.crt
    key: /etc/https/local.key

  # optional support for http2
  http2:
    h2c: true
    max_concurrent_streams: 128

  # Settings for "headers" middleware (docs: https://roadrunner.dev/docs/http-headers).
  headers:
    # Allows to control CORS headers. Additional headers "Vary: Origin", "Vary: Access-Control-Request-Method",
    # "Vary: Access-Control-Request-Headers" will be added to the server responses. Drop this section for this
    # feature disabling.
    cors:
      # Controls "Access-Control-Allow-Origin" header value (docs: https://mzl.la/2OgD4Qf).
      #
      # Default: ""
      allowed_origin: "*"

      # Controls "Access-Control-Allow-Headers" header value (docs: https://mzl.la/2OzDVvk).
      #
      # Default: ""
      allowed_headers: "*"

      # Controls "Access-Control-Allow-Methods" header value (docs: https://mzl.la/3lbwyXf).
      #
      # Default: ""
      allowed_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"

      # Controls "Access-Control-Allow-Credentials" header value (docs: https://mzl.la/3ekJGaY).
      #
      # Default: false
      allow_credentials: true

      # Controls "Access-Control-Expose-Headers" header value (docs: https://mzl.la/3qAqgkF).
      #
      # Default: ""
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"

      # Controls "Access-Control-Max-Age" header value in seconds (docs: https://mzl.la/2PCSdvt).
      #
      # Default: 0
      max_age: 600

    # Automatically add headers to every request passed to PHP.
    #
    # Default: <empty map>
    request:
      Example-Request-Header: "Value"

    # Automatically add headers to every response.
    #
    # Default: <empty map>
    response:
      X-Powered-By: "RoadRunner"

  static:
    dir: "/home/app/src/static"
    forbid: [ ".php" ]
    calculate_etag: false
    weak: false
    allow: [ ".html", ".js", ".css",".png", ".json" ]

grpc:
  listen: "tcp://:9000"
  proto:
    - "/home/app/src/proto/servers/inventory.proto"
  pool:
    num_workers: 1
    max_jobs: 1
    allocate_timeout: 60s
    destroy_timeout: 60
    debug: true
    supervisor:
      # watch_tick defines how often to check the state of the workers (seconds)
      watch_tick: 1s
      # ttl defines maximum time worker is allowed to live (seconds)
      ttl: 0
      # idle_ttl defines maximum duration worker can spend in idle mode after
      # first use. Disabled when 0 (seconds)
      idle_ttl: 60s
      # exec_ttl defines maximum lifetime per job (seconds)
      exec_ttl: 60s
      # max_worker_memory limits memory usage per worker (MB)
      max_worker_memory: 100

#https://docs.roadrunner.dev/docs/queues-and-jobs/kafka
# Kafka jobs driver

jobs:
  consume: [ "default" ]
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 100
  pipelines:
    default:
      driver: memory
      config:
        priority: 10

temporal:
  address: ${TEMPORAL_HOST:-localhost}:${TEMPORAL_PORT:-7233}
  activities:
    debug: true
    num_workers: 1

logs:
  mode: development

  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: debug

reload:
  enabled: true

  # sync interval
  interval: 1s

  # global patterns to sync
  patterns: [".php", ".yaml"]
  # list of included for sync services
  services:
    http:
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs: ["."]

      # recursive search for file patterns to add
      recursive: true
    grpc:
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs: [ "." ]

      # recursive search for file patterns to add
      recursive: true
